version: '3.7'

services:
  app:
    build:
      context: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  static:
  postgres_data: {}