version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=SECRET_KEY
      - ALLOWED_ORIGINS=http://localhost:3000 http://127.0.0.1:3000 http://localhost:8000 http://127.0.0.1:8000 http://localhost
      - ALLOWED_HOSTS=*
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
      - DATABASE_URL=postgresql://username:password@db:5432/dbname

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  static:
  postgres_data: {}

  