# Generated by Django 4.2.4 on 2023-08-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=2040)),
            ],
        ),
    ]
