# Generated by Django 4.2.4 on 2023-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=2040)),
            ],
        ),
    ]
