# Generated by Django 4.2.4 on 2023-08-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2040)),
                ('content', models.TextField()),
            ],
        ),
    ]
